// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: update.proto at 10:1
package com.yuanqi.update.model;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UpdateResponse extends Message<UpdateResponse, UpdateResponse.Builder> {
  public static final ProtoAdapter<UpdateResponse> ADAPTER = new ProtoAdapter_UpdateResponse();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_HAS_UPDATE = false;

  public static final String DEFAULT_VERSION_NAME = "";

  public static final String DEFAULT_UPDATE_LOG = "";

  public static final String DEFAULT_PATH = "";

  public static final String DEFAULT_SIGN = "";

  public static final Boolean DEFAULT_FORCE_UPDATE = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean has_update;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String version_name;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String update_log;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String path;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String sign;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean force_update;

  public UpdateResponse(Boolean has_update, String version_name, String update_log, String path, String sign, Boolean force_update) {
    this(has_update, version_name, update_log, path, sign, force_update, ByteString.EMPTY);
  }

  public UpdateResponse(Boolean has_update, String version_name, String update_log, String path, String sign, Boolean force_update, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.has_update = has_update;
    this.version_name = version_name;
    this.update_log = update_log;
    this.path = path;
    this.sign = sign;
    this.force_update = force_update;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.has_update = has_update;
    builder.version_name = version_name;
    builder.update_log = update_log;
    builder.path = path;
    builder.sign = sign;
    builder.force_update = force_update;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UpdateResponse)) return false;
    UpdateResponse o = (UpdateResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(has_update, o.has_update)
        && Internal.equals(version_name, o.version_name)
        && Internal.equals(update_log, o.update_log)
        && Internal.equals(path, o.path)
        && Internal.equals(sign, o.sign)
        && Internal.equals(force_update, o.force_update);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (has_update != null ? has_update.hashCode() : 0);
      result = result * 37 + (version_name != null ? version_name.hashCode() : 0);
      result = result * 37 + (update_log != null ? update_log.hashCode() : 0);
      result = result * 37 + (path != null ? path.hashCode() : 0);
      result = result * 37 + (sign != null ? sign.hashCode() : 0);
      result = result * 37 + (force_update != null ? force_update.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (has_update != null) builder.append(", has_update=").append(has_update);
    if (version_name != null) builder.append(", version_name=").append(version_name);
    if (update_log != null) builder.append(", update_log=").append(update_log);
    if (path != null) builder.append(", path=").append(path);
    if (sign != null) builder.append(", sign=").append(sign);
    if (force_update != null) builder.append(", force_update=").append(force_update);
    return builder.replace(0, 2, "UpdateResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UpdateResponse, Builder> {
    public Boolean has_update;

    public String version_name;

    public String update_log;

    public String path;

    public String sign;

    public Boolean force_update;

    public Builder() {
    }

    public Builder has_update(Boolean has_update) {
      this.has_update = has_update;
      return this;
    }

    public Builder version_name(String version_name) {
      this.version_name = version_name;
      return this;
    }

    public Builder update_log(String update_log) {
      this.update_log = update_log;
      return this;
    }

    public Builder path(String path) {
      this.path = path;
      return this;
    }

    public Builder sign(String sign) {
      this.sign = sign;
      return this;
    }

    public Builder force_update(Boolean force_update) {
      this.force_update = force_update;
      return this;
    }

    @Override
    public UpdateResponse build() {
      return new UpdateResponse(has_update, version_name, update_log, path, sign, force_update, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UpdateResponse extends ProtoAdapter<UpdateResponse> {
    ProtoAdapter_UpdateResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, UpdateResponse.class);
    }

    @Override
    public int encodedSize(UpdateResponse value) {
      return (value.has_update != null ? ProtoAdapter.BOOL.encodedSizeWithTag(1, value.has_update) : 0)
          + (value.version_name != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.version_name) : 0)
          + (value.update_log != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.update_log) : 0)
          + (value.path != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.path) : 0)
          + (value.sign != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.sign) : 0)
          + (value.force_update != null ? ProtoAdapter.BOOL.encodedSizeWithTag(6, value.force_update) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UpdateResponse value) throws IOException {
      if (value.has_update != null) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.has_update);
      if (value.version_name != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version_name);
      if (value.update_log != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.update_log);
      if (value.path != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.path);
      if (value.sign != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.sign);
      if (value.force_update != null) ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.force_update);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UpdateResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.has_update(ProtoAdapter.BOOL.decode(reader)); break;
          case 2: builder.version_name(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.update_log(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.path(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.sign(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.force_update(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UpdateResponse redact(UpdateResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
