// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: update.proto at 5:1
package me.littlekey.update.model;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UpdateRequest extends Message<UpdateRequest, UpdateRequest.Builder> {
  public static final ProtoAdapter<UpdateRequest> ADAPTER = new ProtoAdapter_UpdateRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_PACKAGE_NAME = "";

  public static final Integer DEFAULT_VERSION_CODE = 0;

  public static final String DEFAULT_CHANNEL = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String package_name;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer version_code;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String channel;

  public UpdateRequest(String package_name, Integer version_code, String channel) {
    this(package_name, version_code, channel, ByteString.EMPTY);
  }

  public UpdateRequest(String package_name, Integer version_code, String channel, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.package_name = package_name;
    this.version_code = version_code;
    this.channel = channel;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.package_name = package_name;
    builder.version_code = version_code;
    builder.channel = channel;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UpdateRequest)) return false;
    UpdateRequest o = (UpdateRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(package_name, o.package_name)
        && Internal.equals(version_code, o.version_code)
        && Internal.equals(channel, o.channel);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (package_name != null ? package_name.hashCode() : 0);
      result = result * 37 + (version_code != null ? version_code.hashCode() : 0);
      result = result * 37 + (channel != null ? channel.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (package_name != null) builder.append(", package_name=").append(package_name);
    if (version_code != null) builder.append(", version_code=").append(version_code);
    if (channel != null) builder.append(", channel=").append(channel);
    return builder.replace(0, 2, "UpdateRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UpdateRequest, Builder> {
    public String package_name;

    public Integer version_code;

    public String channel;

    public Builder() {
    }

    public Builder package_name(String package_name) {
      this.package_name = package_name;
      return this;
    }

    public Builder version_code(Integer version_code) {
      this.version_code = version_code;
      return this;
    }

    public Builder channel(String channel) {
      this.channel = channel;
      return this;
    }

    @Override
    public UpdateRequest build() {
      return new UpdateRequest(package_name, version_code, channel, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UpdateRequest extends ProtoAdapter<UpdateRequest> {
    ProtoAdapter_UpdateRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, UpdateRequest.class);
    }

    @Override
    public int encodedSize(UpdateRequest value) {
      return (value.package_name != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.package_name) : 0)
          + (value.version_code != null ? ProtoAdapter.UINT32.encodedSizeWithTag(2, value.version_code) : 0)
          + (value.channel != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.channel) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UpdateRequest value) throws IOException {
      if (value.package_name != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.package_name);
      if (value.version_code != null) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.version_code);
      if (value.channel != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.channel);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UpdateRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.package_name(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.version_code(ProtoAdapter.UINT32.decode(reader)); break;
          case 3: builder.channel(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UpdateRequest redact(UpdateRequest value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
